

/**
 * This defines the configuration
 */

module.exports = {
  local: {
    API_URL: process.env.API_URL || 'https://127.0.0.1:8443',
    ADMIN_TOOL_URL: process.env.ADMIN_TOOL_URL || 'http://localhost:8080/api/v2',
    API_VERSION_PATH: process.env.API_VERSION_PATH || 'v3',
    COOKIES_SECURE: process.env.COOKIES_SECURE || false,
    AUTH_URL: process.env.AUTH_URL || 'https://accounts.topcoder-dev.com/member',
    ACCOUNTS_CONNECTOR_URL: process.env.ACCOUNTS_CONNECTOR_URL || 'https://accounts.topcoder-dev.com/connector.html',
    JWT_V3_NAME: process.env.JWT_V3_NAME || 'v3jwt',
    JWT_V2_NAME: process.env.JWT_V2_NAME || 'tcjwt',
    BACKEND_API: process.env.BACKEND_API || 'http://localhost:4000',
    DIRECT_URL_BASE: process.env.DIRECT_URL_BASE || 'https://www.topcoder-dev.com/direct/projectOverview?formData.projectId=',
    LABELS: process.env.DIRECT_URL_BASE || ['Open for pickup', 'Assigned', 'Ready for review', 'Paid', 'Feedback', 'Fix accepted'],
    LABELS_COLOR: process.env.LABELS_COLOR || ['112233', '445566', '123123', '456456', 'ff0011', 'aabb11'],
    HOOK_BASE_URL: process.env.HOOK_BASE_URL || 'https://b9602b91.ngrok.io',
    OWNER_LOGIN_GITHUB_URL: '/api/v1/github/owneruser/login',
    OWNER_LOGIN_GITLAB_URL: '/api/v1/gitlab/owneruser/login',
  },
  heroku: {
    API_URL: process.env.API_URL || 'https://api.topcoder-dev.com',
    ADMIN_TOOL_URL: process.env.ADMIN_TOOL_URL || 'https://api.topcoder-dev.com/v2',
    API_VERSION_PATH: process.env.API_VERSION_PATH || 'v3',
    COOKIES_SECURE: process.env.COOKIES_SECURE || false,
    AUTH_URL: process.env.AUTH_URL || 'https://accounts.topcoder-dev.com/member',
    ACCOUNTS_CONNECTOR_URL: process.env.ACCOUNTS_CONNECTOR_URL || 'https://accounts.topcoder-dev.com/connector.html',
    JWT_V3_NAME: process.env.JWT_V3_NAME || 'v3jwt',
    JWT_V2_NAME: process.env.JWT_V2_NAME || 'tcjwt',
    BACKEND_API: process.env.BACKEND_API || 'http://topcoder-x-backend-dev.herokuapp.com',
    DIRECT_URL_BASE: process.env.DIRECT_URL_BASE || 'https://www.topcoder-dev.com/direct/projectOverview?formData.projectId=',
    LABELS: process.env.DIRECT_URL_BASE || ['Open for pickup', 'Assigned', 'Ready for review', 'Paid', 'Feedback', 'Fix accepted'],
    LABELS_COLOR: process.env.LABELS_COLOR || ['112233', '445566', '123123', '456456', 'ff0011', 'aabb11'],
    HOOK_BASE_URL: process.env.HOOK_BASE_URL || 'http://x.topcoder-dev.com/',
    OWNER_LOGIN_GITHUB_URL: '/api/v1/github/owneruser/login',
    OWNER_LOGIN_GITLAB_URL: '/api/v1/gitlab/owneruser/login',
  },
  dev: {
    API_URL: process.env.API_URL || 'https://api.topcoder-dev.com',
    ADMIN_TOOL_URL: process.env.ADMIN_TOOL_URL || 'https://api.topcoder-dev.com/v2',
    API_VERSION_PATH: process.env.API_VERSION_PATH || 'v3',
    COOKIES_SECURE: process.env.COOKIES_SECURE || false,
    AUTH_URL: process.env.AUTH_URL || 'https://accounts.topcoder-dev.com/member',
    ACCOUNTS_CONNECTOR_URL: process.env.ACCOUNTS_CONNECTOR_URL || 'https://accounts.topcoder-dev.com/connector.html',
    JWT_V3_NAME: process.env.JWT_V3_NAME || 'v3jwt',
    JWT_V2_NAME: process.env.JWT_V2_NAME || 'tcjwt',
    DIRECT_URL_BASE: process.env.DIRECT_URL_BASE || 'https://www.topcoder-dev.com/direct/projectOverview?formData.projectId=',
    LABELS: process.env.DIRECT_URL_BASE || ['Open for pickup', 'Assigned', 'Ready for review', 'Paid', 'Feedback', 'Fix accepted'],
    LABELS_COLOR: process.env.LABELS_COLOR || ['112233', '445566', '123123', '456456', 'ff0011', 'aabb11'],
    HOOK_BASE_URL: process.env.HOOK_BASE_URL || 'https://b9602b91.ngrok.io',
    OWNER_LOGIN_GITHUB_URL: '/api/v1/github/owneruser/login',
    OWNER_LOGIN_GITLAB_URL: '/api/v1/gitlab/owneruser/login',
  },
  qa: {
    API_URL: process.env.API_URL || 'https://api.topcoder-qa.com',
    ADMIN_TOOL_URL: process.env.ADMIN_TOOL_URL || 'https://api.topcoder-qa.com/v2',
    API_VERSION_PATH: process.env.API_VERSION_PATH || 'v3',
    COOKIES_SECURE: process.env.COOKIES_SECURE || false,
    AUTH_URL: process.env.AUTH_URL || 'https://accounts.topcoder-qa.com/member',
    ACCOUNTS_CONNECTOR_URL: process.env.ACCOUNTS_CONNECTOR_URL || 'https://accounts.topcoder-qa.com/connector.html',
    JWT_V3_NAME: process.env.JWT_V3_NAME || 'v3jwt',
    JWT_V2_NAME: process.env.JWT_V2_NAME || 'tcjwt',
    BACKEND_API: process.env.BACKEND_API || 'http://localhost:4000',
    DIRECT_URL_BASE: process.env.DIRECT_URL_BASE || 'https://www.topcoder-dev.com/direct/projectOverview?formData.projectId=',
    LABELS: process.env.DIRECT_URL_BASE || ['Open for pickup', 'Assigned', 'Ready for review', 'Paid', 'Feedback', 'Fix accepted'],
    LABELS_COLOR: process.env.LABELS_COLOR || ['112233', '445566', '123123', '456456', 'ff0011', 'aabb11'],
    HOOK_BASE_URL: process.env.HOOK_BASE_URL || 'https://b9602b91.ngrok.io',
    OWNER_LOGIN_GITHUB_URL: '/api/v1/github/owneruser/login',
    OWNER_LOGIN_GITLAB_URL: '/api/v1/gitlab/owneruser/login',
  },
  prod: {
    API_URL: process.env.API_URL || 'https://api.topcoder.com',
    ADMIN_TOOL_URL: process.env.ADMIN_TOOL_URL || 'https://api.topcoder.com/v2',
    API_VERSION_PATH: process.env.API_VERSION_PATH || 'v3',
    COOKIES_SECURE: process.env.COOKIES_SECURE || false,
    AUTH_URL: process.env.AUTH_URL || 'https://accounts.topcoder.com/member',
    ACCOUNTS_CONNECTOR_URL: process.env.ACCOUNTS_CONNECTOR_URL || 'https://accounts.topcoder.com/connector.html',
    JWT_V3_NAME: process.env.JWT_V3_NAME || 'v3jwt',
    JWT_V2_NAME: process.env.JWT_V2_NAME || 'tcjwt',
    BACKEND_API: process.env.BACKEND_API || 'http://topcoderx.topcoder.com:80/api/v1',
    DIRECT_URL_BASE: process.env.DIRECT_URL_BASE || 'https://www.topcoder-dev.com/direct/projectOverview?formData.projectId=',
    LABELS: process.env.DIRECT_URL_BASE || ['Open for pickup', 'Assigned', 'Ready for review', 'Paid', 'Feedback', 'Fix accepted'],
    LABELS_COLOR: process.env.LABELS_COLOR || ['112233', '445566', '123123', '456456', 'ff0011', 'aabb11'],
    HOOK_BASE_URL: process.env.HOOK_BASE_URL || 'https://b9602b91.ngrok.io',
    OWNER_LOGIN_GITHUB_URL: '/api/v1/github/owneruser/login',
    OWNER_LOGIN_GITLAB_URL: '/api/v1/gitlab/owneruser/login',
  },
};
